version: "3.9"

services:
  api:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./setup_db/sqlite_db.py:/code/setup_db/pg_db.py
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5